version: '3'

services:
  Web:
    build:
      context: .
      dockerfile: ./dockerfile
    image: company-web
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 3000:3000
  db:
    image: mongo
    container_name: DB-company
    restart: unless-stopped
    volumes:
      - /mongodata:/data/db
    